name: PHP Composer and PHPUnit tests
on:
  push:
    branches:
    - master
    - devel
    - test
  pull_request:
    branches:
    - master
jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: '${{ runner.os }}-php-

          '
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run test suite
      run: composer run-script test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - ubuntu-20.04
